stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: microsoft/dotnet
      shellScript: dotnet build
- name: Publish
  steps:
  - runScriptConfig:
      image: microsoft/dotnet
      shellScript: |-
        dotnet publish -c Release -r linux-x64 -o out
        cd ./out
        ls
- name: Host
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: microsoft/dotnet
      registry: 127.0.0.1:34320
timeout: 60
notification: {}
