stages:
- name: Compile
  steps:
  - runScriptConfig:
      image: microsoft/dotnet
      shellScript: dotnet build
- name: Publish
  steps:
  - runScriptConfig:
      image: microsoft/dotnet
      shellScript: |-
        dotnet publish -c Release -r linux-x64 -o out
        cd ./out
        ls
- name: Host
  steps:
  - applyAppConfig:
      catalogTemplate: cattle-global-data:helm-drone
      version: 2.0.0-rc.9
      name: helloworld
      targetNamespace: default
timeout: 60
notification: {}
