kind: Service
apiVersion: v1
metadata:
  name: sas
spec:
  selector:
    app: sas
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sas
  labels:
    app: sas
spec:
  replicas: 5
  selector:
    matchLabels:
      app: sas
  template:
    metadata:
      labels:
        app: sas
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: sas
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 80